from __future__ import annotations

from typing import Any


SEARCH_PROVIDERS: list[dict[str, Any]] = [
    {
        "id": "exa_direct",
        "display_name": "Exa Direct API",
        "provider": "exa",
        "status": "active",
        "enabled": True,
        "requires_api_key": True,
        "env_keys_required": ["EXA_API_KEY"],
        "default_enabled": True,
        "supports_keyword_search": True,
        "supports_semantic_search": True,
        "supports_neural_search": True,
        "supports_content_extraction": True,
        "supports_domain_filtering": True,
        "supports_date_filtering": True,
        "supports_highlights": True,
        "supports_structured_sources": True,
        "supports_citations": True,
        "base_cost_per_1000_requests": 7.0,
        "pricing_source": "manual_current_docs",
        "cost_notes": "Exa Search estimate. Actual billing should be verified from Exa dashboard/provider data.",
        "best_for": ["fresh web research", "competitor discovery", "source lists"],
        "default_for_tasks": ["competitor_research", "fresh_research", "website_research"],
        "fallback_provider_ids": ["openai_web_search", "gemini_google_search"],
        "max_results_default": 5,
        "max_results_hard_limit": 10,
        "content_fetch_default": 0,
        "content_fetch_hard_limit": 3,
        "max_cost_per_run_recommended": 0.02,
    },
    {
        "id": "openai_web_search",
        "display_name": "OpenAI Web Search",
        "provider": "openai",
        "status": "active",
        "enabled": True,
        "requires_api_key": True,
        "env_keys_required": ["OPENAI_API_KEY"],
        "requires_approval": True,
        "default_enabled": False,
        "blocked_by_default": True,
        "supports_keyword_search": True,
        "supports_answer_generation": True,
        "supports_structured_sources": True,
        "supports_citations": True,
        "base_cost_per_1000_requests": None,
        "pricing_source": "provider_dependent",
        "cost_notes": "Gated fallback. Use only after explicit approval because cost depends on the selected OpenAI model/tool path.",
        "best_for": ["OpenAI-coupled research answers", "fallback when Exa is unavailable"],
        "avoid_for": ["default research", "mock tests"],
        "default_for_tasks": [],
        "fallback_provider_ids": ["exa_direct"],
        "max_results_default": 5,
        "max_results_hard_limit": 8,
        "max_cost_per_run_recommended": 0.03,
    },
    {
        "id": "gemini_google_search",
        "display_name": "Gemini Google Search",
        "provider": "gemini",
        "status": "active",
        "enabled": True,
        "requires_api_key": True,
        "env_keys_required": ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
        "requires_approval": True,
        "default_enabled": False,
        "blocked_by_default": True,
        "supports_keyword_search": True,
        "supports_google_grounding": True,
        "supports_answer_generation": True,
        "supports_structured_sources": True,
        "supports_citations": True,
        "base_cost_per_1000_requests": None,
        "pricing_source": "provider_dependent",
        "cost_notes": "Gated Google-grounding fallback. Billing may appear later in Google billing export.",
        "best_for": ["Google-grounded research", "freshness-sensitive summaries"],
        "avoid_for": ["default research", "cheap-only runs without approval"],
        "default_for_tasks": [],
        "fallback_provider_ids": ["exa_direct"],
        "max_results_default": 5,
        "max_results_hard_limit": 8,
        "max_cost_per_run_recommended": 0.03,
    },
]
