from __future__ import annotations

from typing import Any


PROVIDERS: list[dict[str, Any]] = [
    {
        "id": "openai",
        "display_name": "OpenAI",
        "key_setting_names": ["openai_api_key"],
        "live_enabled_setting": "allow_live_calls",
        "search_enabled_setting": "enable_openai_web_search",
        "notes": "OpenAI models are blocked from expensive CEO use unless explicit approval is present.",
    },
    {
        "id": "gemini",
        "display_name": "Google Gemini",
        "key_setting_names": ["gemini_api_key", "google_api_key"],
        "live_enabled_setting": "allow_live_calls",
        "search_enabled_setting": "enable_gemini_grounding",
        "notes": "Gemini grounding is treated as search and disabled unless explicitly configured.",
    },
    {
        "id": "openrouter",
        "display_name": "OpenRouter",
        "key_setting_names": ["openrouter_api_key"],
        "live_enabled_setting": "allow_live_calls",
        "search_enabled_setting": "enable_openrouter_search",
        "notes": "OpenRouter account credits are account-level snapshots; per-run cost should use provider response or generation lookup data.",
    },
]


SELECTION_RULES: dict[str, Any] = {
    "blocked_model_phrases": {
        "gpt-5.5": ["do not use gpt-5.5", "don't use gpt-5.5", "no gpt-5.5", "avoid gpt-5.5"],
        "gpt-5.5:flex": ["do not use gpt-5.5", "don't use gpt-5.5", "no gpt-5.5", "avoid gpt-5.5"],
    },
    "cheap_only_phrases": ["cheap models only", "cheap worker models", "low cost", "keep cost low", "use cheap"],
    "search_required_phrases": ["research competitors", "web search", "browse", "latest", "search the web"],
    "tool_required_phrases": ["run command", "safe command", "write file", "edit file", "create files"],
    "high_cost_levels": ["high", "very_high"],
    "safe_fallback_order": ["gpt-5.4-nano", "gemini-3.1-flash-lite", "moonshotai/kimi-k2.7-code", "qwen/qwen3-coder"],
}


PRICING_SNAPSHOTS: list[dict[str, Any]] = [
    {"model_id": "gpt-5.5", "source": "config/manual_assumption", "pricing_is_estimate": True},
    {"model_id": "gpt-5.5:flex", "source": "config/manual_assumption", "pricing_is_estimate": True},
    {"model_id": "gpt-5.4-nano", "source": "config/manual_assumption", "pricing_is_estimate": True},
    {"model_id": "gemini-3.5-flash", "source": "config/manual_assumption", "pricing_is_estimate": True},
    {"model_id": "gemini-3.1-flash-lite", "source": "config/manual_assumption", "pricing_is_estimate": True},
    {"model_id": "moonshotai/kimi-k2.7-code", "source": "config/manual_assumption", "pricing_is_estimate": True},
    {"model_id": "qwen/qwen3-coder", "source": "config/manual_assumption", "pricing_is_estimate": True},
]


MODELS: list[dict[str, Any]] = [
    {
        "id": "gpt-5.5",
        "display_name": "GPT-5.5",
        "provider": "openai",
        "provider_model_name": "gpt-5.5",
        "status": "active",
        "enabled": True,
        "available_for_live": True,
        "requires_approval": True,
        "blocked_by_default": True,
        "default_service_tier": "standard",
        "fallback_models": ["gpt-5.4-nano", "gemini-3.5-flash"],
        "supports_vision": True,
        "supports_multimodal": True,
        "supports_json": True,
        "supports_structured_output": True,
        "supports_function_calling": True,
        "supports_tool_use": True,
        "supports_long_context": True,
        "reasoning_quality": "very_high",
        "coding_quality": "high",
        "writing_quality": "very_high",
        "research_quality": "high",
        "planning_quality": "very_high",
        "math_quality": "high",
        "qa_quality": "very_high",
        "summarization_quality": "very_high",
        "instruction_following_quality": "very_high",
        "speed_level": "medium",
        "latency_notes": "Use sparingly; expected higher latency than worker models.",
        "context_window_tokens": "unknown",
        "max_output_tokens_safe_default": 500,
        "input_cost_per_1m_tokens": 5.0,
        "cached_input_cost_per_1m_tokens": 0.5,
        "output_cost_per_1m_tokens": 30.0,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "openai_reasoning",
        "hosted_provider": "openai",
        "modalities": ["text", "vision"],
        "known_limitations": ["Expensive for routine worker tasks.", "Live use requires explicit approval."],
        "known_strengths": ["Planning", "policy-aware reasoning", "complex synthesis"],
        "known_weaknesses": ["Cost"],
        "best_for": ["CEO planning", "high-stakes synthesis", "complex multi-agent plans"],
        "okay_for": ["QA reviews when approved"],
        "avoid_for": ["cheap worker tasks", "bulk file edits", "routine website copy"],
        "default_agent_roles": ["ceo_agent"],
        "example_tasks": ["Create a complex launch strategy with risk gates."],
        "bad_task_examples": ["Rewrite one HTML heading."],
        "max_cost_per_call_recommended": 0.05,
        "max_cost_per_run_recommended": 0.25,
        "allowed_for_ceo": True,
        "allowed_for_user_visible_outputs": True,
        "requires_human_approval_for_live": True,
        "requires_human_approval_for_high_cost": True,
        "selection_tags": ["ceo", "planner", "high_accuracy", "expensive"],
        "cost_level": "very_high",
        "quality_level": "very_high",
        "preferred_for_high_accuracy": True,
        "approved_for_auto_selection": False,
        "curated_tier": "core",
        "promotion_reason": "Core CEO model, gated because of cost/risk.",
        "auto_selectable": False,
        "notes_for_selector": "Do not auto-select. Requires explicit human approval.",
    },
    {
        "id": "gpt-5.5:flex",
        "display_name": "GPT-5.5 Flex",
        "provider": "openai",
        "provider_model_name": "gpt-5.5",
        "status": "experimental",
        "enabled": True,
        "available_for_live": True,
        "requires_approval": True,
        "blocked_by_default": True,
        "default_service_tier": "flex",
        "fallback_models": ["gpt-5.4-nano", "gemini-3.5-flash"],
        "supports_vision": True,
        "supports_multimodal": True,
        "supports_json": True,
        "supports_structured_output": True,
        "supports_function_calling": True,
        "supports_tool_use": True,
        "supports_long_context": True,
        "reasoning_quality": "very_high",
        "coding_quality": "high",
        "writing_quality": "very_high",
        "research_quality": "high",
        "planning_quality": "very_high",
        "math_quality": "high",
        "qa_quality": "very_high",
        "summarization_quality": "very_high",
        "instruction_following_quality": "very_high",
        "speed_level": "slow",
        "latency_notes": "Flex tier may trade latency for lower estimated cost.",
        "context_window_tokens": "unknown",
        "input_cost_per_1m_tokens": 2.5,
        "cached_input_cost_per_1m_tokens": 0.25,
        "output_cost_per_1m_tokens": 15.0,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "openai_reasoning",
        "hosted_provider": "openai",
        "modalities": ["text", "vision"],
        "known_limitations": ["Still expensive relative to worker models.", "Requires explicit approval."],
        "known_strengths": ["CEO planning", "deep synthesis"],
        "known_weaknesses": ["Latency uncertainty"],
        "best_for": ["approved CEO planning"],
        "okay_for": ["approved complex QA"],
        "avoid_for": ["default live runs", "cheap-only prompts"],
        "default_agent_roles": ["ceo_agent"],
        "max_cost_per_call_recommended": 0.05,
        "max_cost_per_run_recommended": 0.25,
        "allowed_for_ceo": True,
        "requires_human_approval_for_live": True,
        "requires_human_approval_for_high_cost": True,
        "selection_tags": ["ceo", "planner", "high_accuracy", "expensive", "flex"],
        "cost_level": "high",
        "quality_level": "very_high",
        "preferred_for_high_accuracy": True,
        "approved_for_auto_selection": False,
        "curated_tier": "core",
        "promotion_reason": "Core CEO flex-tier option, gated because of cost/risk.",
        "auto_selectable": False,
        "notes_for_selector": "Do not auto-select. Requires explicit human approval.",
    },
    {
        "id": "gpt-5.4-nano",
        "display_name": "GPT-5.4 Nano",
        "provider": "openai",
        "provider_model_name": "gpt-5.4-nano",
        "status": "active",
        "enabled": True,
        "fallback_models": ["gemini-3.1-flash-lite", "qwen/qwen3-coder"],
        "supports_json": True,
        "supports_structured_output": True,
        "supports_function_calling": True,
        "supports_tool_use": True,
        "reasoning_quality": "medium",
        "coding_quality": "medium",
        "writing_quality": "medium",
        "research_quality": "medium",
        "planning_quality": "medium",
        "math_quality": "medium",
        "qa_quality": "medium",
        "summarization_quality": "high",
        "instruction_following_quality": "high",
        "speed_level": "fast",
        "latency_notes": "Preferred low-cost OpenAI worker.",
        "context_window_tokens": "unknown",
        "input_cost_per_1m_tokens": 0.2,
        "cached_input_cost_per_1m_tokens": 0.02,
        "output_cost_per_1m_tokens": 1.25,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "openai_small_worker",
        "hosted_provider": "openai",
        "modalities": ["text"],
        "known_strengths": ["Cheap QA", "structured summaries", "safe worker tasks"],
        "known_weaknesses": ["Not ideal for deep strategy or live web research."],
        "best_for": ["QA Agent", "Content Agent", "Operations Agent", "Provider Test Agent"],
        "okay_for": ["Website copy", "small code review"],
        "avoid_for": ["tasks requiring web search", "expensive CEO reasoning"],
        "default_agent_roles": ["qa_agent", "content_agent", "operations_agent", "provider_test_agent"],
        "example_tasks": ["Review a generated homepage for safety issues."],
        "max_cost_per_call_recommended": 0.01,
        "max_cost_per_run_recommended": 0.05,
        "allowed_for_research": True,
        "allowed_for_website": True,
        "allowed_for_file_builder": True,
        "allowed_for_qa": True,
        "allowed_for_operations": True,
        "selection_tags": ["cheap", "worker", "qa", "content", "operations", "fast"],
        "cost_level": "low",
        "quality_level": "medium",
        "preferred_for_low_budget": True,
        "preferred_for_fast_routing": True,
        "curated_tier": "core",
        "promotion_reason": "Core cheap OpenAI worker already configured in the app.",
        "search_tool_compatible": True,
        "notes_for_selector": "Use for QA, operations, simple text, and low-cost summaries.",
    },
    {
        "id": "gemini-3.5-flash",
        "display_name": "Gemini 3.5 Flash",
        "provider": "gemini",
        "provider_model_name": "gemini-3.5-flash",
        "status": "active",
        "enabled": True,
        "fallback_models": ["gemini-3.1-flash-lite", "gpt-5.4-nano"],
        "supports_vision": True,
        "supports_multimodal": True,
        "supports_json": True,
        "supports_structured_output": True,
        "supports_tool_use": True,
        "supports_long_context": True,
        "reasoning_quality": "high",
        "coding_quality": "medium",
        "writing_quality": "high",
        "research_quality": "high",
        "planning_quality": "high",
        "math_quality": "medium",
        "qa_quality": "high",
        "summarization_quality": "high",
        "instruction_following_quality": "high",
        "speed_level": "fast",
        "latency_notes": "Fast routing and summarization candidate.",
        "context_window_tokens": "unknown",
        "input_cost_per_1m_tokens": 1.5,
        "output_cost_per_1m_tokens": 9.0,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "gemini_flash",
        "hosted_provider": "google",
        "modalities": ["text", "vision"],
        "known_strengths": ["Routing", "summaries", "multimodal reasoning"],
        "known_weaknesses": ["Grounding/search disabled in this v1 unless explicitly enabled."],
        "best_for": ["Model Selector Agent", "Research Agent when search is not required"],
        "okay_for": ["QA", "planning summaries"],
        "avoid_for": ["cheap-only high-volume worker tasks"],
        "default_agent_roles": ["model_selector_agent", "research_agent"],
        "max_cost_per_call_recommended": 0.02,
        "max_cost_per_run_recommended": 0.08,
        "allowed_for_research": True,
        "allowed_for_qa": True,
        "allowed_for_operations": True,
        "selection_tags": ["router", "selector", "research", "summary", "multimodal"],
        "cost_level": "medium",
        "quality_level": "high",
        "preferred_for_multimodal": True,
        "preferred_for_fast_routing": True,
        "curated_tier": "core",
        "promotion_reason": "Core Gemini router/research summarizer already configured in the app.",
        "search_tool_compatible": True,
        "notes_for_selector": "Use for routing and research summaries; search provider is selected separately.",
    },
    {
        "id": "gemini-3.1-flash-lite",
        "display_name": "Gemini 3.1 Flash-Lite",
        "provider": "gemini",
        "provider_model_name": "gemini-3.1-flash-lite",
        "status": "active",
        "enabled": True,
        "fallback_models": ["gpt-5.4-nano", "qwen/qwen3-coder"],
        "supports_vision": True,
        "supports_multimodal": True,
        "supports_json": True,
        "supports_structured_output": True,
        "reasoning_quality": "medium",
        "coding_quality": "medium",
        "writing_quality": "medium",
        "research_quality": "medium",
        "planning_quality": "medium",
        "math_quality": "medium",
        "qa_quality": "medium",
        "summarization_quality": "high",
        "instruction_following_quality": "medium",
        "speed_level": "very_fast",
        "latency_notes": "Fast low-cost Gemini worker.",
        "context_window_tokens": "unknown",
        "input_cost_per_1m_tokens": 0.25,
        "output_cost_per_1m_tokens": 1.5,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "gemini_lite_worker",
        "hosted_provider": "google",
        "modalities": ["text", "vision"],
        "known_strengths": ["Cheap summaries", "fast research drafts"],
        "known_weaknesses": ["Search/grounding not enabled by default."],
        "best_for": ["cheap research drafts", "routing fallback", "summaries"],
        "okay_for": ["QA", "content polishing"],
        "avoid_for": ["deep coding tasks"],
        "default_agent_roles": ["research_agent", "model_selector_agent"],
        "max_cost_per_call_recommended": 0.01,
        "max_cost_per_run_recommended": 0.05,
        "allowed_for_research": True,
        "allowed_for_website": True,
        "allowed_for_qa": True,
        "allowed_for_operations": True,
        "selection_tags": ["cheap", "research", "summary", "fast", "multimodal"],
        "cost_level": "low",
        "quality_level": "medium",
        "preferred_for_low_budget": True,
        "preferred_for_fast_routing": True,
        "curated_tier": "core",
        "promotion_reason": "Core low-cost Gemini research/summarization model already configured.",
        "search_tool_compatible": True,
        "notes_for_selector": "Use for cheap research summaries and QA when no search model coupling is required.",
    },
    {
        "id": "moonshotai/kimi-k2.7-code",
        "display_name": "Kimi K2.7 Code via OpenRouter",
        "provider": "openrouter",
        "provider_model_name": "moonshotai/kimi-k2.7-code",
        "status": "active",
        "enabled": True,
        "fallback_models": ["qwen/qwen3-coder", "gpt-5.4-nano"],
        "supports_json": True,
        "supports_structured_output": True,
        "supports_tool_use": True,
        "reasoning_quality": "high",
        "coding_quality": "very_high",
        "writing_quality": "medium",
        "research_quality": "low",
        "planning_quality": "medium",
        "math_quality": "medium",
        "qa_quality": "medium",
        "summarization_quality": "medium",
        "instruction_following_quality": "high",
        "speed_level": "fast",
        "latency_notes": "Depends on OpenRouter upstream provider.",
        "context_window_tokens": "unknown",
        "input_cost_per_1m_tokens": 0.15,
        "output_cost_per_1m_tokens": 0.6,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "coder",
        "hosted_provider": "openrouter",
        "underlying_provider_if_openrouter": "moonshotai",
        "modalities": ["text", "code"],
        "known_strengths": ["Structured coding edits", "file-aware implementation", "JSON patch planning"],
        "known_weaknesses": ["Not a web search model.", "Provider routing and price may vary."],
        "best_for": ["Real Coding Agent", "Website Agent", "File Builder Agent", "Coding Worker Agent"],
        "okay_for": ["small QA on code changes"],
        "avoid_for": ["CEO planning", "business strategy", "customer-facing claims"],
        "default_agent_roles": ["real_coding_agent", "website_agent", "file_builder_agent", "coding_worker_agent"],
        "max_cost_per_call_recommended": 0.02,
        "max_cost_per_run_recommended": 0.08,
        "allowed_for_website": True,
        "allowed_for_file_builder": True,
        "allowed_for_qa": False,
        "selection_tags": ["coding", "website", "file_builder", "json", "openrouter", "primary_coding_worker"],
        "cost_level": "low",
        "quality_level": "very_high",
        "preferred_for_coding": True,
        "curated_tier": "core",
        "promotion_reason": "Primary OpenRouter coding model for Real Coding Agent v1.",
        "notes_for_selector": "Use for real coding/file edits. Do not use as CEO or search model.",
    },
    {
        "id": "qwen/qwen3-coder",
        "display_name": "Qwen 3 Coder via OpenRouter",
        "provider": "openrouter",
        "provider_model_name": "qwen/qwen3-coder",
        "status": "active",
        "enabled": True,
        "fallback_models": ["gpt-5.4-nano", "gemini-3.1-flash-lite"],
        "supports_json": True,
        "supports_structured_output": True,
        "supports_tool_use": True,
        "reasoning_quality": "medium",
        "coding_quality": "high",
        "writing_quality": "medium",
        "research_quality": "low",
        "planning_quality": "medium",
        "math_quality": "medium",
        "qa_quality": "medium",
        "summarization_quality": "medium",
        "instruction_following_quality": "high",
        "speed_level": "fast",
        "latency_notes": "Depends on OpenRouter upstream provider.",
        "context_window_tokens": "unknown",
        "input_cost_per_1m_tokens": 0.1,
        "output_cost_per_1m_tokens": 0.4,
        "pricing_source": "backend_config_manual_assumption",
        "pricing_is_estimate": True,
        "architecture_family": "coder",
        "hosted_provider": "openrouter",
        "underlying_provider_if_openrouter": "unknown",
        "modalities": ["text", "code"],
        "known_strengths": ["Structured coding edits", "JSON file actions"],
        "known_weaknesses": ["Not a web search model.", "Provider routing may vary."],
        "best_for": ["Website Agent", "File Builder Agent", "Coding Agent"],
        "okay_for": ["QA on code changes"],
        "avoid_for": ["business strategy", "customer-facing claims"],
        "default_agent_roles": ["website_agent", "file_builder_agent", "coding_agent"],
        "max_cost_per_call_recommended": 0.01,
        "max_cost_per_run_recommended": 0.05,
        "allowed_for_website": True,
        "allowed_for_file_builder": True,
        "allowed_for_qa": True,
        "selection_tags": ["cheap", "coding", "website", "file_builder", "json"],
        "cost_level": "very_low",
        "quality_level": "high",
        "preferred_for_low_budget": True,
        "preferred_for_coding": True,
        "curated_tier": "core",
        "promotion_reason": "Core OpenRouter coding model already configured in the app.",
        "notes_for_selector": "Use for website/file work. Do not use OpenRouter for web search.",
    },
    {
        "id": "openrouter-coding-fallback-planned",
        "display_name": "OpenRouter Coding Fallback Candidate",
        "provider": "openrouter",
        "provider_model_name": "unknown",
        "status": "planned",
        "enabled": False,
        "available_for_live": False,
        "fallback_models": ["qwen/qwen3-coder", "gpt-5.4-nano"],
        "coding_quality": "unknown",
        "instruction_following_quality": "unknown",
        "speed_level": "unknown",
        "pricing_source": "provider_discovery_required",
        "pricing_is_estimate": True,
        "best_for": ["future coding fallback after OpenRouter discovery confirms exact model id"],
        "avoid_for": ["automatic selection before promotion"],
        "default_agent_roles": ["website_agent", "file_builder_agent"],
        "allowed_for_website": True,
        "allowed_for_file_builder": True,
        "selection_tags": ["coding", "planned", "openrouter"],
        "cost_level": "unknown",
        "quality_level": "unknown",
        "approved_for_auto_selection": False,
        "curated_tier": "planned",
        "promotion_reason": "Placeholder for a discovered cheap coding model; not selectable until promoted.",
        "auto_selectable": False,
        "notes_for_selector": "Discovery-only/planned. Ignore for normal selection.",
    },
    {
        "id": "openrouter-general-worker-planned",
        "display_name": "OpenRouter General Worker Candidate",
        "provider": "openrouter",
        "provider_model_name": "unknown",
        "status": "planned",
        "enabled": False,
        "available_for_live": False,
        "fallback_models": ["gpt-5.4-nano", "gemini-3.1-flash-lite"],
        "best_for": ["future cheap general worker fallback after discovery"],
        "avoid_for": ["automatic selection before promotion"],
        "default_agent_roles": ["qa_agent", "content_agent"],
        "allowed_for_qa": True,
        "allowed_for_operations": True,
        "selection_tags": ["worker", "planned", "openrouter"],
        "cost_level": "unknown",
        "quality_level": "unknown",
        "approved_for_auto_selection": False,
        "curated_tier": "planned",
        "promotion_reason": "Candidate slot for a discovered low-cost general model.",
        "auto_selectable": False,
        "notes_for_selector": "Discovery-only/planned. Ignore for normal selection.",
    },
    {
        "id": "openrouter-vision-fallback-planned",
        "display_name": "OpenRouter Vision Fallback Candidate",
        "provider": "openrouter",
        "provider_model_name": "unknown",
        "status": "planned",
        "enabled": False,
        "available_for_live": False,
        "supports_vision": True,
        "supports_multimodal": True,
        "best_for": ["future cheap multimodal fallback after discovery"],
        "avoid_for": ["automatic selection before promotion"],
        "selection_tags": ["vision", "planned", "openrouter"],
        "cost_level": "unknown",
        "quality_level": "unknown",
        "approved_for_auto_selection": False,
        "curated_tier": "planned",
        "promotion_reason": "Candidate slot for a discovered low-cost multimodal model.",
        "auto_selectable": False,
    },
    {
        "id": "openai-high-quality-worker-gated",
        "display_name": "OpenAI High-Quality Worker Gated",
        "provider": "openai",
        "provider_model_name": "unknown",
        "status": "planned",
        "enabled": False,
        "available_for_live": False,
        "requires_approval": True,
        "blocked_by_default": True,
        "best_for": ["future high-quality worker fallback if configured"],
        "avoid_for": ["cheap-only tasks", "automatic selection"],
        "selection_tags": ["high_accuracy", "planned", "gated"],
        "cost_level": "high",
        "quality_level": "unknown",
        "approved_for_auto_selection": False,
        "curated_tier": "planned",
        "promotion_reason": "Gated slot only; exact model must be configured before activation.",
        "auto_selectable": False,
    },
    {
        "id": "gemini-grounded-research-gated",
        "display_name": "Gemini Grounded Research Gated",
        "provider": "gemini",
        "provider_model_name": "gemini-3.5-flash",
        "status": "experimental",
        "enabled": True,
        "available_for_live": True,
        "requires_approval": True,
        "supports_web_search": True,
        "supports_json": True,
        "research_quality": "high",
        "summarization_quality": "high",
        "best_for": ["Google-grounded research when Gemini search is enabled"],
        "avoid_for": ["default research when Exa is available"],
        "default_agent_roles": ["research_agent"],
        "allowed_for_research": True,
        "requires_human_approval_for_search": True,
        "selection_tags": ["research", "search", "gemini", "gated"],
        "cost_level": "medium",
        "quality_level": "high",
        "approved_for_auto_selection": False,
        "curated_tier": "experimental",
        "promotion_reason": "Gated model/search pairing; search provider selection is separate.",
        "auto_selectable": False,
        "search_tool_compatible": True,
    },
    {
        "id": "openai-web-search-research-gated",
        "display_name": "OpenAI Web Search Research Gated",
        "provider": "openai",
        "provider_model_name": "gpt-5.4-nano",
        "status": "experimental",
        "enabled": True,
        "available_for_live": True,
        "requires_approval": True,
        "supports_web_search": True,
        "supports_json": True,
        "research_quality": "medium",
        "summarization_quality": "high",
        "best_for": ["OpenAI web search fallback when explicitly requested"],
        "avoid_for": ["default search", "cheap-only tasks without approval"],
        "default_agent_roles": ["research_agent"],
        "allowed_for_research": True,
        "requires_human_approval_for_search": True,
        "selection_tags": ["research", "search", "openai", "gated"],
        "cost_level": "medium",
        "quality_level": "medium",
        "approved_for_auto_selection": False,
        "curated_tier": "experimental",
        "promotion_reason": "Gated OpenAI search pairing; not default.",
        "auto_selectable": False,
        "search_tool_compatible": True,
    },
    {
        "id": "local-mock-research-summarizer",
        "display_name": "Mock Research Summarizer",
        "provider": "mock",
        "provider_model_name": "mock-research-summarizer",
        "status": "active",
        "enabled": True,
        "available_for_live": False,
        "allowed_in_live": False,
        "supports_json": True,
        "research_quality": "low",
        "summarization_quality": "medium",
        "best_for": ["mock-mode research workflow tests without paid calls"],
        "avoid_for": ["live provider runs"],
        "default_agent_roles": ["research_agent"],
        "allowed_for_research": True,
        "selection_tags": ["mock", "research", "test"],
        "cost_level": "free",
        "quality_level": "low",
        "approved_for_auto_selection": True,
        "curated_tier": "fallback",
        "promotion_reason": "Allows no-cost research workflow tests.",
        "auto_selectable": True,
        "search_tool_compatible": True,
    },
]
