from __future__ import annotations

from typing import Any


AGENTS: list[dict[str, Any]] = [
    {
        "id": "business_planner_agent",
        "display_name": "Business Planner",
        "purpose": "Creates Phase 1 business planning artifacts and build handoff without building.",
        "when_to_use": ["business_builder phase 1 planning", "structured business intake"],
        "when_not_to_use": ["website file edits", "Phase 2 builds", "deployments"],
        "allowed_run_types": ["business_builder"],
        "allowed_tools": ["artifact_write", "project_state"],
        "allowed_actions": ["plan", "summarize", "create_build_handoff"],
        "blocked_actions": ["deploy", "package_install", "external_api", "customer_messaging", "payment_integration", "social_posting"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["planner", "cheap", "json"],
        "fallback_models": ["gemini-3.1-flash-lite"],
        "input_context_needed": ["business_intake", "constraints", "memory_state", "search_state"],
        "output_schema": {"planning_artifacts": "markdown_and_json"},
        "success_criteria": ["facts and assumptions separated", "Phase 2 not started", "handoff complete"],
        "failure_modes": ["claims build occurred", "invented market facts", "external action"],
        "qa_checks": ["no website files", "no Real Coding Agent", "no external action"],
    },
    {
        "id": "ceo_agent",
        "display_name": "CEO Agent",
        "purpose": "Plans controlled multi-agent business workflows and safety handoffs.",
        "when_to_use": ["business launch plans", "complex strategic planning"],
        "when_not_to_use": ["website-only edits", "provider connectivity tests"],
        "allowed_run_types": ["business_launch_plan", "prototype_build"],
        "allowed_tools": ["artifact_write"],
        "allowed_file_scopes": [],
        "allowed_actions": ["plan", "delegate", "summarize"],
        "blocked_actions": ["deploy", "package_install", "external_api", "customer_messaging"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["planner", "high_accuracy"],
        "fallback_models": ["gpt-5.4-nano"],
        "requires_approval_for": ["gpt-5.5_live"],
        "input_context_needed": ["command", "project_state"],
        "output_schema": {"plan": "markdown"},
        "memory_needed": ["current_state", "project_summary"],
        "success_criteria": ["safe scope", "agent order", "approval gates"],
        "failure_modes": ["over-selects agents", "asks for risky actions"],
        "qa_checks": ["no deploy", "no public claims"],
    },
    {
        "id": "model_selector_agent",
        "display_name": "Model Selector Agent",
        "purpose": "Selects low-risk, budget-aware models from the registry.",
        "when_to_use": ["every agent needing a model"],
        "when_not_to_use": ["manual command runner steps"],
        "allowed_run_types": ["business_launch_plan", "prototype_build", "continuation", "website_update", "provider_test", "business_builder"],
        "allowed_tools": ["model_registry_read"],
        "allowed_actions": ["select_model"],
        "blocked_actions": ["live_upgrade_without_approval"],
        "default_models": ["gemini-3.5-flash", "gpt-5.4-nano"],
        "preferred_model_tags": ["selector", "fast"],
        "fallback_models": ["gpt-5.4-nano"],
        "output_schema": {"selected_model_id": "string", "reason": "string"},
        "success_criteria": ["structured JSON", "no secret leakage", "cost guard respected"],
        "failure_modes": ["selects blocked model", "ignores cheap-only"],
        "qa_checks": ["candidate filtered before prompt"],
    },
    {
        "id": "research_agent",
        "display_name": "Research Agent",
        "purpose": "Produces conservative research briefs; search only when enabled and approved.",
        "when_to_use": ["competitor research", "market research", "launch plans"],
        "when_not_to_use": ["website-only copy polish unless research requested"],
        "allowed_run_types": ["business_launch_plan", "prototype_build", "website_update", "research_only", "research", "business_builder"],
        "allowed_tools": ["artifact_write", "web_search"],
        "allowed_actions": ["summarize", "research"],
        "blocked_actions": ["external_api", "customer_messaging"],
        "default_models": ["gemini-3.1-flash-lite"],
        "preferred_model_tags": ["research", "summary", "cheap"],
        "fallback_models": ["gpt-5.4-nano"],
        "can_use_search": True,
        "requires_approval_for": ["web_search"],
        "success_criteria": ["clearly marks assumptions", "reports search unavailable if disabled"],
        "failure_modes": ["pretends to browse", "states unverified facts as true"],
        "qa_checks": ["no fake current facts"],
    },
    {
        "id": "website_agent",
        "display_name": "Website Agent",
        "purpose": "Updates website/project files inside approved project scopes.",
        "when_to_use": ["homepage updates", "website files", "copy/layout changes"],
        "when_not_to_use": ["business launch plans without file changes"],
        "allowed_run_types": ["website_update", "prototype_build", "continuation"],
        "allowed_tools": ["project_file_write"],
        "allowed_file_scopes": ["website/"],
        "allowed_actions": ["read_project_files", "write_project_files"],
        "blocked_actions": ["deploy", "package_install", "external_api", "payment_integration"],
        "default_models": ["qwen/qwen3-coder", "gpt-5.4-nano"],
        "preferred_model_tags": ["coding", "website", "cheap"],
        "fallback_models": ["gpt-5.4-nano"],
        "can_write_files": True,
        "requires_approval_for": ["external_actions"],
        "input_context_needed": ["project_state", "current_files"],
        "output_schema": {"file_actions": []},
        "memory_needed": ["project_summary", "recent_qa"],
        "success_criteria": ["files stay under website/", "no deployment", "QA follows file changes"],
        "failure_modes": ["edits outside scope", "adds dependencies"],
        "qa_checks": ["validate changed files", "safe command if code changed"],
    },
    {
        "id": "content_agent",
        "display_name": "Content Agent",
        "purpose": "Writes controlled copy and launch content.",
        "when_to_use": ["content calendar", "copywriting", "brand positioning"],
        "when_not_to_use": ["website-only code edits"],
        "allowed_run_types": ["business_launch_plan", "prototype_build"],
        "allowed_tools": ["artifact_write"],
        "allowed_actions": ["draft_copy", "summarize"],
        "blocked_actions": ["social_posting", "customer_messaging"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["content", "cheap"],
        "fallback_models": ["gemini-3.1-flash-lite"],
        "success_criteria": ["claims marked for approval"],
        "failure_modes": ["public claims without approval"],
        "qa_checks": ["no medical/nutrition overclaiming"],
    },
    {
        "id": "operations_agent",
        "display_name": "Operations Agent",
        "purpose": "Defines safe manual operating procedures.",
        "when_to_use": ["launch plans", "order flow", "manual approval process"],
        "when_not_to_use": ["website-only visual/copy update"],
        "allowed_run_types": ["business_launch_plan", "prototype_build"],
        "allowed_tools": ["artifact_write"],
        "allowed_actions": ["plan_operations"],
        "blocked_actions": ["payments", "supplier_sourcing", "customer_messaging"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["operations", "cheap"],
        "fallback_models": ["gemini-3.1-flash-lite"],
        "success_criteria": ["manual approvals clear"],
        "failure_modes": ["assumes real operational capability"],
        "qa_checks": ["no payment/customer action"],
    },
    {
        "id": "file_builder_agent",
        "display_name": "File Builder Agent",
        "purpose": "Converts approved file tasks into safe project file writes.",
        "when_to_use": ["prototype file creation", "continuation file updates"],
        "allowed_run_types": ["prototype_build", "continuation", "website_update"],
        "allowed_tools": ["project_file_write"],
        "allowed_file_scopes": ["website/", "docs/", "content/"],
        "allowed_actions": ["write_project_files"],
        "blocked_actions": ["secret_files", "package_install", "deploy"],
        "default_models": ["qwen/qwen3-coder", "gpt-5.4-nano"],
        "preferred_model_tags": ["file_builder", "coding", "cheap"],
        "fallback_models": ["gpt-5.4-nano"],
        "can_write_files": True,
        "success_criteria": ["safe JSON file actions"],
        "failure_modes": ["invalid JSON", "unsafe path"],
        "qa_checks": ["path scope", "safe extensions"],
    },
    {
        "id": "safe_command_runner",
        "display_name": "Safe Command Runner",
        "purpose": "Runs allowlisted validation commands with full cwd/stdout/stderr logging.",
        "when_to_use": ["after file changes", "test runner UI"],
        "allowed_run_types": ["prototype_build", "continuation", "website_update"],
        "allowed_tools": ["safe_command"],
        "allowed_actions": ["py_compile", "pytest", "npm_lint", "npm_build"],
        "blocked_actions": ["shell_escape", "package_install", "deploy"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["cheap"],
        "can_run_safe_commands": True,
        "needs_model_selection": False,
        "success_criteria": ["logs cwd", "logs executable", "captures stderr/stdout"],
        "failure_modes": ["wrong cwd", "hidden exception"],
        "qa_checks": ["exit code respected"],
    },
    {
        "id": "qa_agent",
        "display_name": "QA Agent",
        "purpose": "Reviews outputs, file changes, command logs, and safety constraints.",
        "when_to_use": ["every workflow with output"],
        "allowed_run_types": ["business_launch_plan", "prototype_build", "continuation", "website_update", "provider_test", "business_builder"],
        "allowed_tools": ["artifact_write"],
        "allowed_actions": ["review", "summarize"],
        "blocked_actions": ["external_api", "deploy"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["qa", "cheap"],
        "fallback_models": ["gemini-3.1-flash-lite"],
        "success_criteria": ["flags assumptions", "checks constraints"],
        "failure_modes": ["misses blocked action"],
        "qa_checks": ["verify run mode/cost source"],
    },
    {
        "id": "provider_test_agent",
        "display_name": "Provider Test Agent",
        "purpose": "Runs one tiny live provider connectivity test.",
        "when_to_use": ["provider_test run type only"],
        "allowed_run_types": ["provider_test"],
        "allowed_tools": ["provider_call"],
        "allowed_actions": ["tiny_provider_test"],
        "blocked_actions": ["file_write", "safe_command", "external_actions"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["cheap", "worker"],
        "requires_live": True,
        "success_criteria": ["one tiny provider response", "usage captured"],
        "failure_modes": ["provider unavailable"],
        "qa_checks": ["no files or commands"],
    },
    {
        "id": "project_workspace_manager",
        "display_name": "Project Workspace Manager",
        "purpose": "Maintains project_state, manifest, run logs, and file change history.",
        "when_to_use": ["project file workflows"],
        "allowed_run_types": ["prototype_build", "continuation", "website_update", "business_builder"],
        "allowed_tools": ["project_manifest", "project_state"],
        "allowed_actions": ["update_manifest", "update_project_state"],
        "blocked_actions": ["edit_secret_files"],
        "default_models": ["gpt-5.4-nano"],
        "preferred_model_tags": ["cheap"],
        "success_criteria": ["state and manifest reflect actual changes"],
        "failure_modes": ["stale project_state"],
        "qa_checks": ["manifest matches file changes"],
    },
]


AGENT_RULES: dict[str, Any] = {
    "negative_constraints": {
        "deploy": ["do not deploy", "don't deploy", "no deploy", "no deployment"],
        "package_install": ["do not install packages", "don't install packages", "no package installs", "do not install dependencies"],
        "external_actions": ["no external actions", "do not use external actions", "don't use external actions"],
        "email": ["do not send emails", "don't send emails", "no emails"],
        "social_posting": ["do not post", "don't post", "no social posting"],
        "gpt-5.5": ["do not use gpt-5.5", "don't use gpt-5.5", "no gpt-5.5"],
        "file_writes": ["do not create files", "do not write files", "do not update files", "no file writes"],
        "commands": ["do not run commands", "do not execute commands", "no commands"],
    },
    "workflow_defaults": {
        "business_builder": ["business_planner_agent", "qa_agent"],
        "website_update": ["website_agent", "qa_agent"],
        "provider_test": ["provider_test_agent"],
        "research_only": ["research_agent", "qa_agent"],
        "business_launch_plan": ["ceo_agent", "research_agent", "content_agent", "operations_agent", "qa_agent"],
    },
}
